name: Python CI/CD Workflow
 
on: [push]
 
jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python

      uses: actions/setup-python@v2

      with:

        python-version: 3.8

    - name: Install Dependencies

      run: |

        python -m pip install --upgrade pip

        pip install -r requirements.txt

    - name: Run Tests

      run: python -m unittest discover
 
  deploy:

    needs: test

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Git to use the token

      run: |

        git config user.name "PrithviJayachandraM"

        git config user.email "prithvijayachandra@gmail.com"

        git remote set-url origin https://x-access-token:${{ secrets.CICD }}@github.com/PrithviJayachandraM/SpamApp.git

    - name: Create and push to deployment branch

      run: |

        git checkout -b deploy

        git push -f origin deploy  # Using force push here
